name: flutter_web_admin_template
description: Experiment on Flutter web for Admin dashboard..

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  skadi: ^0.1.2
  future_manager: ^1.0.0
  provider: ^6.0.3
  dio: ^4.0.6
  sentry: ^6.5.1
  go_router: ^3.1.0
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  ##UI
  fl_chart: ^0.50.6
  device_preview: ^1.1.0
  flutter_riverpod: ^1.0.3
  oktoast: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
